# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whcBx-7mzkIchMWHPSrRbbeqDg2D4uw2
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

!ls -la "/content/drive/My Drive/darknet-master"

!git clone https://github.com/Shraddha2013/customyolo.git
# %cd customyolo

!ls

!git checkout feature/google-colab

!make

!wget https://pjreddie.com/media/files/darknet53.conv.74

!./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74

!wget https://pjreddie.com/media/files/yolov3.weights

!./darknet detect cfg/yolo-obj.cfg yolov3.weights "/content/drive/My Drive/IMG-20191008-WA0021.jpg"

!./darknet detector train data/obj.data yolo-obj.cfg darknet53.conv.74 -map

!./darknet yolo test cfg/yolo-obj.cfg yolov3.weights "/content/drive/My Drive/IMG-20191009-WA00361.jpg" -thresh 0

import cv2
from google.colab.patches import cv2_imshow
path = r'/content/drive/My Drive/IMG-20191009-WA00361.jpg'
image = cv2.imread(path)
window_name = 'image'
cv2_imshow(image)